### ISSUE TITLE
Add table of contents to blog

### ISSUE THREAD

**Issue by TheJiahao** [TheJiahao/TheJiahao.github.io#5]
### Card minimalistic

![Image](https://github.com/TheJiahao/TheJiahao.github.io/assets/42709836/f7f8726d-c62a-47fc-a5c1-cb2b6d330466)

### Card minimalistic fill

![Image](https://github.com/TheJiahao/TheJiahao.github.io/assets/42709836/345c3825-5fc1-4269-95c3-bf90dc978bf2)

### Card fill

![Image](https://github.com/TheJiahao/TheJiahao.github.io/assets/42709836/807fecf8-0b4b-48bb-90af-73278d5f7dcd)

## Tasks

- [x] Add table of contents
- [x] Indent subheadings
- [x] Adjust style
- [x] Highlight current section, [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)
  - [x] Use Intersection Observer in `TableOfContents` to get current section id
  - [x] Pass section id to `TableOfContentsHeading`
  - [x] Adjust style if id matches inside `TableOfContentsHeading`
- [x] Tests

## Useful links

- [react-intersection-observer](https://www.npmjs.com/package/react-intersection-observer)
- https://kld.dev/building-table-of-contents/
- https://billyle.dev/posts/highlight-table-of-content-items-using-intersection-observer
- https://rezahedi.dev/blog/create-table-of-contents-in-astro-and-sectionize-the-markdown-content
- https://kld.dev/toc-animation/#marking-active-links
